In [1]:
import pandas as pd
import numpy as np

In [2]:
titanic = pd.read_csv('titanic.csv')
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
df = titanic.drop(['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked'], axis=1)
df.head()

Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [4]:
gender_dummies = pd.get_dummies(df.Sex)
gender_dummies.head()

female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [ ]:
df = pd.concat([df, gender_dummies], axis='columns')
df.head()

#### I am dropping male column as well because of dummy variable trap theory. One column is enough to repressent male vs female

In [6]:
df.drop(['Sex', 'male'], axis=1, inplace=True)
df.head()

Survived  Pclass   Age     Fare  female
0         0       3  22.0   7.2500       0
1         1       1  38.0  71.2833       1
2         1       3  26.0   7.9250       1
3         1       1  35.0  53.1000       1
4         0       3  35.0   8.0500       0

#### Checking if any column contains Nan value

In [14]:
df.columns[df.isna().any()]

Index(['Age'], dtype='object')

#### Filling Nan values in Age cloumn

In [17]:
df.Age = df.Age.fillna(df.Age.mean())
df.head()

Survived  Pclass   Age     Fare  female
0         0       3  22.0   7.2500       0
1         1       1  38.0  71.2833       1
2         1       3  26.0   7.9250       1
3         1       1  35.0  53.1000       1
4         0       3  35.0   8.0500       0

In [19]:
input = df.drop('Survived', axis=1)
target = df.Survived

In [20]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(input, target, test_size = 0.3)

#### importing GaussianNB

In [22]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [23]:
model.fit(x_train, y_train)

GaussianNB()

In [24]:
y_predicted = model.predict(x_test)
y_predicted

array([0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0], dtype=int64)

In [28]:
model.predict_proba(x_test)

array([[9.63686386e-01, 3.63136135e-02],
       [4.40295692e-01, 5.59704308e-01],
       [9.13843319e-01, 8.61566813e-02],
       [3.63638386e-02, 9.63636161e-01],
       [2.13721233e-02, 9.78627877e-01],
       [1.90994751e-02, 9.80900525e-01],
       [9.70585367e-01, 2.94146334e-02],
       [2.45022268e-01, 7.54977732e-01],
       [2.40306087e-01, 7.59693913e-01],
       [2.22532538e-01, 7.77467462e-01],
       [4.12341027e-01, 5.87658973e-01],
       [8.51510246e-01, 1.48489754e-01],
       [9.33292363e-01, 6.67076374e-02],
       [9.62479299e-01, 3.75207012e-02],
       [9.59758330e-01, 4.02416703e-02],
       [9.20559445e-01, 7.94405547e-02],
       [1.92249003e-01, 8.07750997e-01],
       [4.27828046e-01, 5.72171954e-01],
       [9.68871785e-01, 3.11282148e-02],
       [9.68884976e-01, 3.11150240e-02],
       [3.90642201e-02, 9.60935780e-01],
       [9.56796214e-01, 4.32037859e-02],
       [9.67157934e-01, 3.28420661e-02],
       [9.68474791e-01, 3.15252085e-02],
       [9.705571

In [29]:
model.score(x_test, y_test)

0.7574626865671642

In [31]:
from sklearn.model_selection import cross_val_score
score = cross_val_score(GaussianNB(), x_train, y_train, cv=5)
score

array([0.784     , 0.776     , 0.776     , 0.79032258, 0.7983871 ])

In [33]:
x_test[:2]

Pclass   Age    Fare  female
623       3  21.0  7.8542       0
276       3  45.0  7.7500       1

In [35]:
model.predict([[1, 33, 10, 1]])

array([1], dtype=int64)