In [1]:
import numpy as np

In [14]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

### Implement Mean Absolute Error

In [15]:
def mae(y_predicted, y_true):
    total_error = 0;
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print('Total Error :', total_error)
    mae = total_error / len(y_true)
    print('Mean Absolute Error :', mae)
    return mae

In [16]:
mae(y_predicted, y_true)

Total Error : 2.5
Mean Absolute Error : 0.5


0.5

### Implement Mean Absolute Error using numpy

In [17]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [18]:
np.mean(np.abs(y_predicted-y_true))

0.5

In [19]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted - y_true))

In [20]:
mae_np(y_predicted, y_true)

0.5

### Implement Log Loss or Binary Cross Entropy

In [22]:
np.log([0])

<ipython-input-22-faee82fd9f21>:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [23]:
epsilon = 1e-15

In [24]:
np.log([epsilon])

array([-34.53877639])

In [38]:
y_predicted

array([1, 1, 0, 0, 1])

##### changing zero's to values which will be very close to zero and changing 1 to value very close to 1

In [30]:
y_predicted_new = [max(i, epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [31]:
1-epsilon

0.999999999999999

In [35]:
y_predicted_new = [min(i, 1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [37]:
y_predicted_new = np.array(y_predicted_new)
y_predicted_new

array([1.e+00, 1.e+00, 1.e-15, 1.e-15, 1.e+00])

In [39]:
def log_loss(y_predicted, y_true):
    y_predicted_new = [max(i, epsilon) for i in y_predicted]
    y_predicted_new = [min(i, 1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true * np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [40]:
log_loss(y_predicted, y_true)

17.2696280766844

### Implement Log Loss or Binary Cross Entropy

In [49]:
def mse(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += (yp - yt)**2
    print('Total Error :', total_error)
    mse = total_error/len(y_predicted)
    print('Mean Squared Error :', mse)
    return mse

In [50]:
mse(y_predicted, y_true)

Total Error : 1.83
Mean Squared Error : 0.366


0.366

#### Implement Log Loss or Binary Cross Entropy

In [53]:
def mse_np(y_predicted, y_true):
    return np.mean(np.square(y_predicted - y_true))
#     return np.mean((y_predicted - y_true)**2)

In [54]:
mse_np(y_predicted, y_true)

0.366