In [71]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np

In [4]:
iris = load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [6]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [7]:
df['target'] = iris.target
df.head(1)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   

   target  
0       0

In [10]:
df['flower_name'] = df.target.apply(lambda x : iris.target_names[x])
df.head(4)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   

   target flower_name  
0       0      setosa  
1       0      setosa  
2       0      setosa  
3       0      setosa

In [12]:
x = df.drop(['target', 'flower_name'], axis=1)
y = df.target

### Importing models

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

### importing Cross Val Score

In [17]:
from sklearn.model_selection import cross_val_score

### LogisticRegression score

In [70]:
lr_score = cross_val_score(LogisticRegression(max_iter=3500), x, y, cv=3)
lr_score
print(lr_score)
print(np.mean(lr_score))

[0.98 0.96 0.98]
0.9733333333333333


### SVM Score

In [69]:
# C = Regularization
svm_score_C = cross_val_score(SVC(C=13), x, y, cv=3)
svm_score_C
print(svm_score_C)
print(np.mean(svm_score_C))

[0.98 1.   0.96]
0.98


In [68]:
# linear kernel 
svm_score_linear = cross_val_score(SVC(kernel='linear'), x, y, cv=3)
svm_score_linear
print(svm_score_linear)
print(np.mean(svm_score_linear))

[1.   1.   0.98]
0.9933333333333333


In [67]:
# poly kernel
svm_score_poly = cross_val_score(SVC(kernel='poly'), x, y, cv=3)
svm_score_poly
print(svm_score_poly)
print(np.mean(svm_score_poly))

[0.98 0.94 0.98]
0.9666666666666667


In [66]:
# rbf kernel (Radial-basis function kernel)
svm_score_rbf = cross_val_score(SVC(kernel='rbf'), x, y, cv=3)
svm_score_rbf
print(svm_score_rbf)
print(np.mean(svm_score_rbf))

[0.96 0.98 0.94]
0.96


### RandomForest score

In [63]:
# n_estmators is no of tress in forest
rf_score = cross_val_score(RandomForestClassifier(n_estimators=50), x, y, cv=3)
print(rf_score)
print(np.mean(rf_score))

[0.98 0.94 0.98]
0.9666666666666667


### DecisionTreeClassifier score

In [64]:
dtree_score = cross_val_score(DecisionTreeClassifier(), x, y, cv=3)
print(dtree_score)
print(np.mean(dtree_score))

[0.98 0.92 0.96]
0.9533333333333333
